server:
  port: 8003
mybatis:
  type-aliases-package:  cn.org.july.springcloud.api.entities            #所以entity别名类所在路径

spring:
  application:
    name: springcloud-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                        #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver                         #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/cloudDB03?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false                          #数据库连接
    username: root
    password: root
    dbcp2:
      min-idle: 5                                                       #数据库连接池的最小维持连接数
      initial-size: 5                                                   #初始化连接数
      max-total: 5                                                      #最大连接数
      max-wait-millis: 200                                              #等待连接获取的最大超时时间

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      registerWithEureka: true
      fetchRegistry: true
  instance:
    instance-id: springcloud-user-8003
    prefer-ip-address: true

info:
  app.name: springcloud-user
  company.name: www.july.com
  build.artifactId: springcloud
  build.version: 1.0-SNAPSHOT